### ISSUE TITLE
Autoselect default Category and Subcategory on Payee selection

### ISSUE THREAD

**Issue by marcel-hofer** [okaufmann/laravel-web-money-manager-ex#60]
The MMEX Client sends Payees (json data) with the following two Fields:
- DefCateg
- DefSubCateg

Selecting such a payee should automatically (clear existing and) select the default ones.
This was implemented in the previous version (before the laravel rewrite).

See sample JSON in [feature test](https://github.com/okaufmann/laravel-web-money-manager-ex/blob/master/tests/Feature/MmexClient/PayeeTest.php#L32)

**Comment by okaufmann** [comment]
Since all categories will be deleted after payees were imported, all default category selections were deleted either.
